### ISSUE TITLE
Can I set my heatmapshader to a solid color?

### ISSUE THREAD

**Issue by xx1425942154** [Osongpodo/HeatmapShader#1]
boss, I changed the shader to hide four colors and use red. I want to see the effect of a solid color, but I found that the color value of each pixel is a little different, but I found that the shader is not supported. Can you handle it? Thank you, boss

**Comment by Osongpodo** [comment]
Thank you for your question! I will quickly fix this error!

**Comment by Osongpodo** [comment]
The error you mentioned has been corrected! It was a LayerMask issue.

**Comment by Osongpodo** [comment]
![image](https://github.com/Osongpodo/HeatmapShader/assets/73912947/5b137b2b-5d10-4c4b-b1ca-555b5515acb5)

**I created the shader you mentioned and added it!**
